- 0/0.6/0.6.md
Datos del integrante 06 Luis Núñez
> Presentación Integrante 06

- 0/0.4/0.4.md
He agregado los datos personales del integrante 4
> Datos personales

- 0/0.4/0.4.md
Se realizaron cambios en los datos personales del integrante 4.
> Actualización de datos

- 0/0.4/0.4.md
Agregué los datos de mi módulo
> Fabio-Castillo: Lab 2

- _avances/detalle-modulos/04-ModuloProcesoProduccion.md
- _avances/detalle-modulos/ProcesoProduccion_1.md
Se añade la definición y respuesta de las preguntas solicitadas.
> Lisseth-Arnao; Lab2

- _avances/detalle-modulos/01-MODULO DE GESTION DE INSUMOS.md
- _avances/detalle-modulos/02-MODULO DE GESTION DE INSUMOS.md
Se respondió a las preguntas de la clase del modulo gestión de insumos.
> Alexis-Boza; Lab2 

- 1/1.1/1.1.md
Confirmo que esos son los cambios que quiero realizar.
> He agregado los datos de la empresa que me habian asignado como tarea.

- 1/1.1/1.1.md
Corregí algunos datos de la empresa.
> Actualización de datos de la empresa

- 1/1.4/1.4.md
#24 
**Descripción del trabajo:**
- Se añadió la sección 1.4. Entrevista al documento principal en formato .md.
- Se incorporó un enlace a la entrevista subida a YouTube, incluyendo una miniatura.
- Se redactó un resumen de los temas tratados durante la entrevista.
- Se creó un canal de YouTube donde se subirán todos los recursos audiovisuales relacionados al desarrollo del curso.
**Notas adicionales:**
- La entrevista fue grabada, editada para una mejor visualización y publicada como material de apoyo para el equipo, según lo indicado por el profesor.
- El canal de YouTube servirá como repositorio de entrevistas, presentaciones y demostraciones relevantes del proyecto.
> Entrevista

- 1/1.2/1.2.md
#26 
Se corrigió el contenido del archivo 1.2.md y se agregó detalles de cada sección del Canvas relacionado a la empresa.
> Contenido del Modelo de Negocio

- 4/4.2/4.2.md
- 5/5.2/5.2.md
Se corrigió el diccionario de datos
> Raigarcia 00

- 5/5.3/5.3.md
Se añadió la explicación de la creación de la tabla DosificadoxLote_Insumo.
> Se registraron los ajustes del modelo

- 4/4.2/4.2.md
Agregué algunas entidades pertenecientes a mi módulo.
> Diccionario de datos - Actualización

- 4/4.2/4.2.md
Se añadió el diccionario de datos.
> Actualizacion - Modulo 2

- 5/5.2/5.2.md
Se agrego las entidades de almacén en el diccionario de datos.
> Diccionario de Datos - Modelo Relacional

- 2/2.2/2.2.md
> Listado de modulos

- 5/5.3/5.3.md
Agregué un nuevo caso de relación de muchos a muchos proveniente de mi módulo, que hace referencia al Proveedor y el Insumo.
> Tabla intermediaria de N:M

- 0/0.8/0.8.md
- 0/0.8/PC1/0.8.1.md
> Se añadio video individual modulo 1

- 3/3.2/3.2.md
Se detallo mejor la descripción de lo caos de Uso.
> Correcion de los casos de Uso

- 4/4.2/4.2.md
- 5/5.2/5.2.md
- 5/5.3/5.3.md
Corregí ciertos aspectos que noté como errores respecto al modelado de las entidades que uso en mi módulo (Compras), entre ellos está:
- Contemplar el nuevo atributo formado en los atributos pertenecientes a las entidades con la que trabaja mi módulo.
- Mejoramiento en la documentación de ajustes al modelo
- Corrección en el atributo ID_PROPUESTA_COMPRA en el diccionario del modelo relacional.
> Correción del modelado

- 4/4.2/4.2.md
- 5/5.2/5.2.md
1. Se agregaron entidades y tablas generales (no pertenecen a algún módulo en específico, pero son importantes para el modelado general por lo que algunos integrantes se encargarán de determinadas entidades/tablas).
2. Se agruparon las tablas por módulos para una mejor apreciación de la distribución de trabajo por integrante
> Modificación de los diccionarios

- 4/4.2/4.2.md
- 5/5.2/5.2.md
Fix Diccionario de datos conceptual y relacional del módulo Proceso Productivo
> Corrección de Diccionario Proceso Productivo

- 5/5.2/5.2.md
Se corrigió el diccionario Relacional desacuerdo a los cambios del diccionario conceptual y al modelo relacional.
> Corrección del diccionario Relacional - Modulo de Almacén de Insumos

- 4/4.2/4.2.md
- Se reorganizó el diccionario conceptual para el módulo de calidad, uniendo los atributos comunes de las inspecciones en la entidad padre "Inspección General".
- Se implementó la especialización de inspecciones en 4 entidades hijas: Inspección_LoteInsumo, Inspección_Proceso, Inspección_Envasado, e Inspección_Picking.
- Se estandarizaron atributos compartidos como: fecha, hora, estado_revision, comentario y evidencia.
- Se eliminaron booleanos redundantes y se reemplazaron por atributos descriptivos como motivo_rechazo, tipo_defecto_empaque, motivo_defecto_picking y detalle_fallo_proceso.
- Justificación de diseño: Se optó por especialización para facilitar mantenimiento, evitar duplicidad, unificar trazabilidad y permitir futura extensión de tipos de inspección con distinta lógica o …
> feat(diccionario): restructuración del diccionario conceptual para calidad e implementación de especialización para inspecciones

- 5/5.2/5.2.md
- Se completó el diccionario relacional del módulo de Control de Calidad.
- Se definió la entidad principal "Inspección General" con clave primaria ID_INSPECCION (SERIAL) y atributos comunes (fecha, hora, estado, comentario, evidencia).
- Las entidades hijas (Inspección_LoteInsumo, Inspección_Proceso, Inspección_Envasado, Inspección_Picking) fueron definidas con claves primarias que también son claves foráneas hacia Inspección_General (herencia 1:1).
- Se normalizaron todos los campos categóricos mediante "lookup tables" para:
- motivo_rechazo_insumo
- tipo_defecto_empaque
- motivo_defecto_picking
- tipo_fallo_proceso
- Las relaciones entre inspecciones y procesos (Mezclado, Moldeado, Secado, Envasado, Picking) se establecieron mediante claves foráneas explícitas y nullables donde …
> feat(diccionario-relacional): reestructuración del modelo relacional para el módulo de control de calidad

- 7/7.1/7.1.md
- Se añade parte del script para la creación de tablas referentes al módulo de Control de Calidad
> Corrección de la creación de tablas del módulo de Control de Calidad

- 7/7.2/7.2.md
Se colocaron datos ficticios para simular un escenario real dentro de la Empresa respecto al Módulo de Control de Calidad
> Poblamiento de datos en las Tablas del Módulo de Control de Calidad

- 5/5.2/5.2.md
Se actualizo el diccionario relacional de los modulos de control de produccion y mantenimiento para que este acorde a las tablas creados y a los datos insertados
> Actualizacion del diccionario relacional segun la creacion de las tablas y la poblacion de datos

- 6/6.1/6.1.md
- 6/6.2/6.2.md
Se realizó según lo indicado por temas de tiempo, el diseño físico de la tabla "INSPECCION_GENERAL" del módulo de Control de Calidad
> Se realizó el diseño físico de una tabla del módulo de Control de Calidad

- 6/6.1/6.1.md
- 6/6.2/6.2.md
Se subio los parametros fisico y la estimacion de registros por tablas de los modulos de control de produccion y mantenimiento
> Diseño Fisico

- 6/6.1/6.1.md
- 6/6.2/6.2.md
Se añadieron la estimación de cantidad de registros y los parámetros físicos correspondientes al módulo de compras.
> Módulo de compras en la carpeta 6.

- 6/6.2/6.2.md
Se añadió los parámetros físicos de la tabla recepciones.
> Diseño físico - Almacén de Insumos 

- 6/6.1/6.1.md
Se añadió la estimación de los registros.
> Parámetro Físico Estimacion- Almacén de insumos 

- 0/0.8/PC2/0.8.2.md
Corresponde a adjuntar el video de PC2.
> se añadio el video correspondiente a la pc2

- 0/0.8/PC2/0.8.2.md
Video de PC2 Modulo de control de produccion y mantenimiento, alumno Rai Garcia Isuiza
> Adjunto video de la PC2

- 7/7.1/CreacionTablas.sql
- Se reorganizó la parte del script de creación de las tablas del Módulo de Control de Calidad.
- Se establecieron correctamente las claves foráneas entre las entidades especializadas (mezclado, moldeado, secado).
- Se eliminaron registros inválidos o inconsistentes para evitar errores de integridad.
- Se reescribieron los inserts en `InspeccionesProceso` utilizando `id_proceso_recurrente` y `tipo_proceso`, manteniendo la normalización con ProcesosRecurrente.
- Se verificó la compatibilidad de claves foráneas con tablas dependientes como `SolicitudesMantenimiento`.
> Se corrigió la creación de Tablas del Módulo de Control de Calidad

- 4/4.2/4.2.md
- 5/5.2/5.2.md
Del Diccionario Modelo Conceptual:
- Se corrigieron los nombres de las entidades
- Se eliminó los atributos que no correspondían
- Se editó los nombres de los atributos para normalizarlo con el resto de entidades
Del Diccionario Modelo Relacional:
- Se corrigieron los nombres de las entidades
- Se corrigió el tipo de dato para los casos ENUM y TIMESTAMP para las fechas
- Se eliminó los atributos que no corresponden
- Se normalizó el nombre de algunos atributos
> fix(DiccionarioConceptual y DiccionarioRelacional) Modelo Proceso Produccion

- 7/7.1/7.1.md
- 7/7.2/7.2.md
Se redactaron los documentos en formato MD, indicando las reglas, lógica y formatos a seguir en los scribds realizados en PostreSQL.
> Redacción de los documentos pertenecientes a la carpeta 7.1 y 7.2

- 4/4.2/4.2.md
- 5/5.2/5.2.md
- 5/5.3/5.3.md
Luego de haber realizado la creación de tablas y el poblamiento de datos relacionados al módulo de compras, se notaron ciertos errores, pues habían tablas o datos que no cumplían necesariamente con lo que se indicaba en los diccionarios, los cuales se corrigieron para tener un trabajo con mejor entendimiento, se cambió:
- Diccionario del modelado conceptual
- Diccionario del modelado relacional
- Documentación de ajustes al modelo
> Módulo de Compras: Corrección Diccionarios

- 6/6.1/6.1.md
- 6/6.2/6.2.md
- 7/7.1/CreacionTablas.sql
- 7/7.2/Poblamiento.sql
Se realizaron varias mejoras respecto al módulo de compras pertenecientes a la segunda práctica:
- Corrección de Estimación Cantidad de Registros
- Corrección de Parámetros Físicos
- Corrección de la Creación de Tablas
- Corrección del Poblamiento de Datos
> Módulo Compras - Mejoras Generales

- 5/5.2/5.2.md
- 7/7.1/CreacionTablas.sql
- 7/7.2/Poblamiento.sql
1. Se comentaron especificaciones en el script y se modificó el diccionario del modelo relacional acorde al script en sus especificaciones del formato de los atributos
2. Mi modulo de Distribucion presentó un cambio para añadir el catalogo, acorde a las nuevas indicaciones del profesor, se procedió a comentarlo y no tenerlo en cuenta porque **no se debe alterar la estructura** para el parcial
3. Se mejoró el script de CreateTable para que pueda compilar agregando un DROP TYPE del estado_eclamo_enum
> Correcciones diccionario modelo relacional
